### ISSUE TITLE
app crashes after googlePlayServices update

### ISSUE THREAD

**Issue by 4malik** [myflashlab/common-dependencies-ANE#12]
I started to add Firebase in my project so i added googlePlayServices: base, basement, iid.
At start my app crashes without any visible errors. Cant see logcat logs cause have no root access yet on device. 
After some attempts i tried to use old versions of that libs and project starts successfully.

java 1.8u111
air sdk 25
flash develop 5.2.0
flex 4.16

**Comment by myflashlab** [comment]
It is VERY probable that you have not added all the dependencies. This page must be your best reference. https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

Anyhow, considering that this question is related to Firebase ANE, I am closing this one. More questions about Firebase, please use its own GitHub page. Thanks.
