### ISSUE TITLE
Warning: unable to load SWC overrideAir.ane

### ISSUE THREAD

**Issue by wigginsray** [myflashlab/common-dependencies-ANE#17]
In Adobe Animate V18.0 - AIR 27.0.0.116 - Windows 10
On Testing (CTRL-ENTER) - I get "Warning: unable to load SWC overrideAir.ane"
On Publishing for IOS - I get an error "Installation Error: PackageExtractionFailed"

My goal is to implement the Augmented Reality ANE using Adobe Animate as my IDE. I hope this is possible.

1. Added overrideAir.exe to the Library Path (added as an ANE)
2. This is essentially a clean project with little else in it at this point.
3. If I expand the overrideAir.ane in the library path tab (advanced actionscript 3.0 settings) it says "invalid native extension (ANE) file. I've downloaded the latest version I believe 5.0. It also shows the ane in the included files (Air for IOS Settings). 
4. If I remove the *.ane and publish, the app publishing successfully (albeit the app in only a black square at this time - just trying to remove certifications/provisioning/IO issues
5. I also tried using the overrideAir.swc - but no joy there either.

File size of my overrideAir.ane file is 33,624 bytes.

Please advise.

I have an older version of the *.ane that appears to import correctly - but I'm not sure if using the older one will compromise what I'm doing with Augmented Reality/Wikitude.

**Comment by myflashlab** [comment]
It seems like you have downloaded a corrupted version of the overrideAir and. It's fine size is about 170kb.

However, you may safely use the older version. V4.1.0

**Comment by myflashlab** [comment]
any more question on this regard?
