### ISSUE TITLE
inAppPayment ANE doesnt work 

### ISSUE THREAD

**Issue by usmanredsoft-zz** [myflashlab/common-dependencies-ANE#21]
we have purchase inAppPayment ANE but it doesnt work very poor even we sent a email to customer support team but they not helping us....

Want to ask question to "myflashlabs" team if you not provide good quality service product or help you should dont right to selling bad product... it was our mistake we select ATM myflashlabs ANE... we strongly recommend ```removed``` great work + great help always.... 

regards
~ Saif

**Comment by myflashlab** [comment]
Please let us know what the problem is. link to the problem if still available.

**Comment by usmanredsoft-zz** [comment]
No need any more help, we already went to use MilkMan plugin it more great product..
