### ISSUE TITLE
Possible event override problem

### ISSUE THREAD

**Issue by mtilhan** [myflashlab/common-dependencies-ANE#22]
Hi,

I'am using GoogleSignIn-ANE with freshplanet/ANE-Facebook and 
GoogleSignIn-ANE needs **overridAir**  to work.

So when i add GoogleSignIn-ANE and overridAir to project (even not code implementation, just adding extension) facebook ANE not work properly. It's stuck on login screen and cant finish login process if we choose log in with Facebook Application option.

It's looks like some event overrided from other ANE and the application cant finish process. So 
i suspect overridAir beacuse i find similar problems in past issues.

So i have no idea to solution. What can i do to work both ANE's properly? Is there an option we do not use overridAir?

**Comment by myflashlab** [comment]
the overrideAIR is the core of our ANEs and it links all our ANEs to each other. so, no, you can't drop that. However, you may use our [Facebook ANE](https://github.com/myflashlab/facebook-ANE/) and resolve the possible conflicts.

**Comment by myflashlab** [comment]
closing the issue because of inactivity.
