### ISSUE TITLE
New OverrideAir.ane doesn't work

### ISSUE THREAD

**Issue by AlexUrrutia** [myflashlab/common-dependencies-ANE#24]
Hello @myflashlab , After several hours trying, using the demo project: https://github.com/myflashlab/Firebase-ANE

Runtime Errors:
`[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.`

![screen shot 2018-10-01 at 7 16 49 pm](https://user-images.githubusercontent.com/7042361/46322455-9a639900-c5ae-11e8-88dc-1cad6b6764f9.png)

**Then I removed the updated OverrideAir.ane and replaced with the previous version and the project compiled and run on device without problems, what am I missing from the new OverrideAir.ane ?**

**Comment by myflashlab** [comment]
We are not experiencing a problem with v5.1.4 Will you please send over the AS3 code you have when using/calling the ```OverrideAir``` class?

**Comment by myflashlab** [comment]
in the logs you sent, the _os value is set to ```android```. but the _context is null. This gives me a feeling that the ANE itself is not implemented in your binary. maybe a name missing in your IDE? could you verify that? 

Basically V5.1.4 is identical to the previous version and the only difference is that we are detecting ```IOS_SIM``` to know if the ANE is running on iOS simulator or not. So, it should be working fine.

**Comment by AlexUrrutia** [comment]
That is weird, I'm using IntelliJ with the demo project from your repository [https://github.com/myflashlab/Firebase-ANE](url)

So no idea why is doing that, very strange

**Comment by myflashlab** [comment]
I don't know what to suggest :thinking: We are not able to duplicate the problem and no one else is reporting a similar thing. OverrideAir ANE is being used in ALL our ANEs so if no one else is reporting a problem with the latest version, then there must be something weird going on in your project :) That's the best conclusion I was able to come up with! :D

**Comment by AlexUrrutia** [comment]
changed OverrideAir ANE location to the same folder where the source app files are and it works now, strange...
