### ISSUE TITLE
hi, I use different ANE and in this way, I get the error.

### ISSUE THREAD

**Issue by flashomer** [myflashlab/common-dependencies-ANE#26]
hi, I use different ANE and in this way, I get the error.

androidSupport-v4.ane  = http://prntscr.com/l6geiv
overrideAir.ane = http://prntscr.com/l6gjq8
androidSupport-core.ane = http://prntscr.com/l6gi8z

http://prntscr.com/l6gfew

the program does not work when you remove any of them. :/

extensions: 
```
<extensionID>com.distriqt.MediaPlayer</extensionID>
<extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
<extensionID>com.distriqt.androidsupport.V4</extensionID>
<extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
<extensionID>com.myflashlab.air.extensions.webView</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
```

**Comment by myflashlab** [comment]
Such ANE conflicts happen when using different providers. You may consider using a video player solution we have? instead of the MediaPlayer currently used?

I may need to close the issue though because this is an ANE conflict problem.

**Comment by flashomer** [comment]
I want to use video player solution however, i have to use it because it has android notification ( http://prntscr.com/l6niue ). Therefore, we have to solve this problem. Please, help me.
