### ISSUE TITLE
Error #1063: Argument count mismatch on com.myflashlab.air.extensions.dependency::OverrideAir$/applyToAneLab(). Expected 1, got 0.

### ISSUE THREAD

**Issue by AlexUrrutia** [myflashlab/common-dependencies-ANE#29]
Just updated the dependencies and I got this error:

`[Fault] exception, information=ArgumentError: Error #1063: Argument count mismatch on com.myflashlab.air.extensions.dependency::OverrideAir$/applyToAneLab(). Expected 1, got 0.`

**Comment by myflashlab** [comment]
That’s right, you need to update your other ANEs too. They are connected.

**Comment by AlexUrrutia** [comment]
I have updated everything, and I keep getting that error,  should I create the firebaseCore again?

**Comment by myflashlab** [comment]
1. Let us know the list of ANEs you’re using.
2. Are you using ANELAB?

**Comment by AlexUrrutia** [comment]
OK I had to create the **firebaseCore.ane** again, that was it, thanks!
