### ISSUE TITLE
platformoptions.xml

### ISSUE THREAD

**Issue by esdebon** [myflashlab/common-dependencies-ANE#3]
The common dependencies is a great idea... but I can't generate my ANE correctly, I think that my problem is the platformoptions.xml file... How can I add the packagedResource ? 

Can you share an example of a correct platformoptions.xml file?

**Comment by myflashlab** [comment]
The Common dependency ANEs are adding required Android libraries to your project. You don't need to modify them at all. Just embed them in your project and the library will be available to the rest of your ANEs in the project.
