### ISSUE TITLE
App crashes after sending push notification through FCM

### ISSUE THREAD

**Issue by shaktisinghtanwar** [myflashlab/common-dependencies-ANE#32]
I have successfully implemented the FCMcore ane and firebase messaging ane in my project. when i send push notification after receiving the token the app has stopped and crashed. 

com.myflashlab.air.extensions.firebase.core(AirCommand) command:initFirebase
com.myflashlab.air.extensions.firebase.core(AirCommand) initFirebase > passed the initial initialization
com.myflashlab.air.extensions.firebase.core(AirCommand) initFirebase > initialization completed
checkGoogleAvailability result = SUCCESS
token: flf9X3dzGZA:APA91bE6_HM6CIBRhg-Xa7W9iqqRKNo-15OVP__9o-RY1hJxfRaCGAyo4PU9oU2JZFfS5gX0K_uGttB8IyuofSlLW-yztVEn7fUnlVw-KHgd7fIF0TagG6WPRpErvALdt364MnWAkR2L

i have implemented all the dependencies so why i am getting this error

Adobe sdk 30
Android 8

**Comment by myflashlab** [comment]
For tech questions about commercial ANEs, please use our new private/secure platform. re-download the packages you have purchased and there's a readme file there explaining how to use the premium support package.
