### ISSUE TITLE
Error: Duplicate platform default found for extension

### ISSUE THREAD

**Issue by Gohloum** [myflashlab/common-dependencies-ANE#36]
Hello,

I have an application that uses the webview ane.  It was compiling to the ADT simulator without any issues.  I began to work on an android build and was getting some errors.  I found that my overrideAir package was old, so I updated it.  Now I can not get anything to compile with the latest version.  See the error below.

[AIR Debug Launcher]: The content cannot be loaded because there was a problem loading an extension: Error: Duplicate platform default found for extension com.myflashlab.air.extensions.dependency.overrideAir

I tried switching back to the previous ANE (V5.1.3), but now still getting the same error.  Any idea what I need to look at?

**Comment by Gohloum** [comment]
You can close this ticket.  I found the issue to be a combination of older ANEs that needed updating and duplicate entries in the .iml file (IntelliJ)  When I updated the ANE files,  for some reason IntelliJ did not update my .iml file correctly and I have both a global and project reference entry for override air, even though I completely deleted the project level lib from the project settings.  The solution was to go into the .iml file, find the duplicates, removed them, close and relaunch IntelliJ.   Maybe this feedback will help any others who may run into issues while updating your ANE libs.

**Comment by myflashlab** [comment]
Thanks for the comments. probably another solution to avoid such conflicts is to not specifying the ANEs one by one into intelliJ and instead introduce a folder for it so you can add/remove ANEs from that folder and intelliJ will add all ANEs found in that folder.
