### ISSUE TITLE
RichWebView.init() fails.

### ISSUE THREAD

**Issue by Gohloum** [myflashlab/common-dependencies-ANE#37]
Hello,

I am getting the following runtime error:

[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.
at com.myflashlab.air.extensions.dependency::OverrideAir()
at com.myflashlab.air.extensions.dependency::OverrideAir$/applyToAneLab()
at com.myflashlab.air.extensions.richWebView::RichWebView()
at com.myflashlab.air.extensions.richWebView::RichWebView$/init()

I have all the ANEs setup and linked to my project, and I am able to build and run on android via USB.  However I was getting the above error on startup.  So I moved the offending RichWebView.init() call to a button press to make sure the app was running and working.  

I have the following linked to my project via the app.xml:

`
        <extensionID>com.myflashlab.air.extensions.richWebView</extensionID>
        <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.customtabs</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
 <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>`

And here is the android manifest:

<android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			    
			    
		
			    <uses-permission android:name="android.permission.INTERNET"/>
			    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
			    
			    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    <uses-sdk android:targetSdkVersion="26"/>
			    
			    <application android:hardwareAccelerated="true" android:allowBackup="true">
                    
                    
                    <activity android:name="com.myflashlabs.richwebview.Pick" android:theme="@style/Theme.Transparent" />
            
                    
                    <receiver android:name="com.myflashlabs.richwebview.ChromeTabActionBroadcastReceiver" />
            
                </application>
			</manifest>
		]]></manifestAdditions>
    </android>

Any advice as to why I can not initialize the RichWebView?

**Comment by myflashlab** [comment]
for tech support on commercial ANEs you should use our private/secure support platform.
