### ISSUE TITLE
Cannot compile in AIR SDK (32.0.0.89). Apple has removed support for libstdc++ from Xcode10 (iOS12). All the native static libraries used in ANE, which are built with libstdc++ will not work with the latest AIR SDK

### ISSUE THREAD

**Issue by cjittipanit** [myflashlab/common-dependencies-ANE#39]
We cannot compile in AIR 32. The same code can compile in AIR 31

OS: Windows 10
AIR: 32.0.0.58

List of library that we using: 
```xml
<extensions>
    <extensionID>com.myflashlab.air.extensions.webView</extensionID>
    <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.customtabs</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector.impl</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.measurementBase</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.stats</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.badge</extensionID>
    <extensionID>com.myflashlab.air.extensions.pdfViewer</extensionID>
  </extensions>
```

Please  re-new version ANE(s) for support in AIR 32 iOS12

![image](https://user-images.githubusercontent.com/47619005/55448647-be9e4200-55f2-11e9-914f-a50370b683ae.png)

Changing in  AIR 32
[https://helpx.adobe.com/flash-player/release-note/fp_32_air_32_release_notes.html](url)

**iOS SDK Upgrade**
AIR Runtime is now built with iOS 12 SDK, which enables AIR developers to use ANEs built with iOS 12 APIs without using the –platformSDK switch while packaging with ADT.

To use existing ANEs built with earlier iOS version:

Apple has removed support for libstdc++ from Xcode10 (iOS12). All the native static libraries used in ANE, which are built with libstdc++ will not work with the latest AIR SDK. It will throw the below error. The static library has to be rebuilt with Xcode 10 and repackaged.
Error : ld: library not found for -lstdc++
ld: library not found for -lstdc++
Compilation failed while executing : ld64

**Comment by myflashlab** [comment]
This error is not related to iOS 12.1. You've just missed to [copy the frameworks](https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md) to the new AIR SDK.

This questions is not related to dependencies so I'm closing it.

For tech questions about ANEs, you should use our private, secure support platform.
