### ISSUE TITLE
Problem with Multiple ANEs.

### ISSUE THREAD

**Issue by ten2ng** [myflashlab/common-dependencies-ANE#41]
I am using the myflashlab Admob-ANE and Flash Builder 4.6.
When I Add the package overrideAir.ane and androidSupport.ane I get the error 'Multiple ANEs with the same NativeLibrary classes.jar are being packaged' .
It shows for Google Android only. Apple iOS isn't show this error.
I don't have any ane or extensions.
It is same problem with closed ticket #10 but I couldn't find answer there.

Please give me the advice.
thanks

**Comment by ten2ng** [comment]
Please give advice. I already bought the ANEs for Admob but It doesn't work. It you can't fix this matter you should refund it to me.

**Comment by myflashlab** [comment]
Tech questions are answered in our private/secure support platform. The Admob ANE is one of our most popular ANEs and many are using it with no problem, so we'd be happy to help you get it to work. Please make sure you have the latest version of the ANE downloaded, then check the "ReadMeFirst.txt" file in the zip file and there you'll have all the required information on how to contact/submit tech questions to our private support platform.

Thanks.
