### ISSUE TITLE
Error aapt tool when generate apk

### ISSUE THREAD

**Issue by radiocold** [myflashlab/common-dependencies-ANE#47]
When I generate the apk show me this error: 

aapt tool failed:Failed to generate resource table for split '
AppData\Local\Temp\9e6c68b2-28b6-4ce-8b53-578bb46490ac\androidx.appcompat-res\values-v28\values-v28.xml:7 error: Error:No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius')

I used the last version of Adobe AIR 32.0.0 and the common anes files.
Please I can´t generate the apk

**Comment by jkpatel1463** [comment]
Hello @radiocold

You can update Adobe Air version and fix this issues. 

Here is link by which you can download latest version of Adobe air(33.1)
https://airsdk.harman.com/

After updating Adobe Air SDK, You have to update java version to 1.8. Here is link to solve ajor.minor version 51.0's issues:
https://github.com/Gamua/Adobe-Runtime-Support/issues/310

**Comment by radiocold** [comment]
Yes , I solved it. . My version Adobe SDK AIR was old. Thanks
