### ISSUE TITLE
no tags? is master branch ok for use with firebase ane 3.0

### ISSUE THREAD

**Issue by Helgiii** [myflashlab/common-dependencies-ANE#6]
is master branch ok for use with firebase ane 3.0?
thanx

**Comment by myflashlab** [comment]
Always try to use the latest version. the latest Firebase ANE is V4 at the moment. If you need to use older versions, find the appropriate dependencies by visiting the older branches as described here: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md#v300
