### ISSUE TITLE
Missing resource files in androidSupport.ane

### ISSUE THREAD

**Issue by steven-cerebralfix** [myflashlab/common-dependencies-ANE#8]
When I include androidSupport.ane in my project I get the following compile error attempting to package the Android build. It does not happen with the earlier version of androidSupport.ane.

aapt tool failed:C:\Users\...\AppData\Local\Temp\05518e99-c05f-45b2-8382-fdd922fd5334\android.support.v7.appcompat-res\values-v23\values-v23.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

C:\Users\...\AppData\Local\Temp\05518e99-c05f-45b2-8382-fdd922fd5334\android.support.v7.appcompat-res\values-v23\values-v23.xml:34: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

C:\Users\...\AppData\Local\Temp\05518e99-c05f-45b2-8382-fdd922fd5334\android.support.v7.appcompat-res\values-v24\values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

C:\Users\...\AppData\Local\Temp\05518e99-c05f-45b2-8382-fdd922fd5334\android.support.v7.appcompat-res\values-v24\values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

**Comment by myflashlab** [comment]
Are you using AIR SDK 25?

**Comment by steven-cerebralfix** [comment]
Ah, no I'm using AIR SDK 23.

**Comment by myflashlab** [comment]
@steven-cerebralfix So, is the problem fixed?

**Comment by lordlinton** [comment]
Thanks yes it does work on AIR25. I'm using this with your Google Play Services plugin and had been using AIR23 as I didn't want to deal with the new permissions polava in AIR24+. Looks like I'll have to bite the bullet and update.

**Comment by reatailret** [comment]
Don't work with AIR23 . Problem with appcompat-v7.jar , cardview-v7.jar

**Comment by myflashlab** [comment]
@reatailret with higher AIR SDKs, you should be fine. I'm closing the issue but if anything, please do let us know and we'll continue on this.
